main = do
  let x = 4
  print(x)
  
  -- x = 5 --error
  print(x)
